[package]
name = "pascaltree"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = "0.3.7"
num-bigint = "0.4"
num-traits = "0.2.19"
pbr = "1.1.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
